### ISSUE TITLE
Achievement Unlocked Timestamp?

### ISSUE THREAD

**Issue by pfeiferchristopher** [syntaxerrors/Steam#25]
I've noticed that on the Steam website you can see when an achievement was unlocked. I hate to be a bother but since you found my other request so quickly, how about this one?

Based on this http://stackoverflow.com/questions/23612350/steam-achievements-api-how-to-get-achievement-unlocking-date it seems that `unlockTimestamp` is only available for "newer" achievements but I figure if the Steam website has it, then it probably can be found lol. At least hopefully.

**Comment by stygiansabyss** [comment]
Yeah. I'll get this in tonight.

**Comment by pfeiferchristopher** [comment]
Awesome! Thanks.

**Comment by stygiansabyss** [comment]
Knew I remembered that link title from last night.  So that is going through the XML parsing of a steam profile page.  It does not go through the API.  To get this working may take a bit more since the core classes were not built to handle XML calls.  I'll start looking into it now.

Side note, feel free to hop in Gitter chat anytime if you need something specific.
