### ISSUE TITLE
app()->appDetails only takes one parameter now, key not needed

### ISSUE THREAD

**Issue by rannmann** [syntaxerrors/Steam#5]
Requests to  http://store.steampowered.com/api/appdetails/ do not require an API key to query, but instead are rate limited by IP.  Additionally, comma-separated lists of application IDs result in a 400 response.

Everything still works if you only pass one app ID.  Just thought I'd give a heads up.

For fun:
Users commenting about the `appids` change.  Apparently sometimes Valve re-enables using multiple app IDs, and then reverts the change. Classy! https://www.reddit.com/r/Steam/comments/2kz2ay/steam_store_api_multiple_app_id_lists_no_longer/

**Comment by stygiansabyss** [comment]
The appdetails one I'll leave as is for simplicity.  Passing the key doesn't hurt anything since it will just be ignored.  For the rate limit I would suggest just implementing a local caching solution.

Regarding the multiple appids, that really does suck, but there is not much I can do to correct that.  I could add in flags to switch between passing them at once and looping through, but that would greatly slow down an application.
