### ISSUE TITLE
Fix expected response to GetUserStatsForGame tests.

### ISSUE THREAD

**Issue by nicekiwi** [syntaxerrors/Steam#89]
Tests should reflect the functionality of the code, with the Steam API as unstable as it it; a test should not fail just because the steam API is down/broken/weird. 

Recently the `ISteamUserStats/GetUserStatsForGame` API is returning 500 errors for valid requests. The code to get the UserStats is still valid; but the API breaking causes the test to fail. 

Where do we strike a balance of knowing(ish) when an API is failing and when our own code is failing?

IMO we should fire exceptions when it fails and test for both cases, but not using live Data.

Thoughts? @stygiansabyss

**Comment by nicekiwi** [comment]
I'm happy to write/re-write the tests too.

**Comment by stygiansabyss** [comment]
I normally don't write tests that test things I didn't write as its too up in the air to be reliable.  In the case of the steam API, those are the exact reasons I did it.  The goal was to try and add some reliability to the steam API.  if they change something, the tests would find it and in turn alert me to update the code to match.

Now, if there are ones that are failing, but the API has 100% definitively not changed, then that's a problem.  It might be best to look for certain errors and consider them "safe failures" and just log them instead of failing for them.  Just check the code returned and catch the safe ones, throw the unexpected ones.

Thoughts?

**Comment by nicekiwi** [comment]
Ahhh, I see! Travis is setup to run monthly, and if the tests had been working that would have worked fine. 

In this case, it works until your request is valid; as in it verifies if required tokens are valid, and when they are it returns 500 error. So we could modify the test to expect that and hope that fails in the future when it starts working again.. and note it in the README.

**Comment by stygiansabyss** [comment]
That would make sense.

**Comment by nicekiwi** [comment]
Fix in commit 99fa2d389ab1fa23e09c8280940eaf7e0ff8bec2
